### ISSUE TITLE
Add a new service SUDOC

### ISSUE THREAD

**Issue by lrichelle** [ExLibrisGroup/alma-refine#14]
Hi, 
Would it be possible to add a new service for IdRef authorities?
The reconciliation service is  http://refine.codefork.com/reconcile/viaf/SUDOC

We're going to change our authority priority configuration in Alma in order to use IdRef from CZ - and it will be usefull for us to get IdRef URIs for some headings.

Thanks in advance !
Laurence

**Comment by jweisman** [comment]
Hi @lrichelle - thanks for your request. Can you help with the following information:
* Some sample records that use the SUDOC authority
* Relevant fields and the associated index (from their list of Person, Corporate Name, Geographic Name, Work, Expression)
For BNF, we used the following:
      { "tag": "1xx", "subfield": "a", "indexes": [], "subfield2": [], "hints": ["b", "d"] },
      { "tag": "6xx", "subfield": "a", "indexes": [], "subfield2": [], "hints": [] },
      { "tag": "75x", "subfield": "a", "indexes": ["/location/location"], "subfield2": [], "hints": ["b", "d"] },
      { "tag": "7xx", "subfield": "a", "indexes": [], "subfield2": [], "hints": ["b", "d"] }

Thanks,

**Comment by lrichelle** [comment]
Hi,
Here is a sample file
[BIBLIOGRAPHIC_30254859820002321_1.zip](https://github.com/ExLibrisGroup/alma-refine/files/5844358/BIBLIOGRAPHIC_30254859820002321_1.zip)

I have this in Alma production for BNF :
Tag 100 Subfield a Indexes Person Hint Subfields b c d
Tag 700 Subfield a Indexes Person, Work, Expression Hint Subfields b c d
Tag 710 Subfield a Indexes Corporate Name, Work, Expression
Tag 130 Subfield a Indexes  Work, Expression
Tag 600 Subfield a Indexes Person, Work, Expression Hint Subfields b c d
Tag 610 Subfield a Indexes Corporate Name, Work, Expression Hint Subfields t
Tag 630 Subfield a Indexes  Work, Expression
Tag 651 Subfield a Indexes  Geographic Name
Tag 751 Subfield a Indexes  Geographic Name
Is this what you asked?

cheers,
laurence

**Comment by jweisman** [comment]
Hi- thanks for your feedback. We've added the service in beta mode. Please give it a try and let us know how it works for you.

**Comment by lrichelle** [comment]
Hi, 
It works fine, great.

Still bad, like for BNF, is the Correct term functionality : for exemple, in mms id  990019274020502321, the heading has been corrected : $$a Simon, Neil, 1927-2018. $$d 1927-2018 $$e auteur $$4 aut $$1 https://www.idref.fr/029311632
What's wrong here is that the dates have been added in $a. 
At this stage, It would be usefull to edit the record directly from the Refine job in order to correct the heading manually.
Have a nice day
laurence

**Comment by jweisman** [comment]
Thanks for your confirmation. Glad it works with SUDOC.

Unfortunately, the service returns the name with the dates. See [this example](https://conciliator.herokuapp.com/reconcile/viafproxy/SUDOC?queries=%7B%22104826f9%22:%7B%22query%22:%22Pe%CC%81rez-Simon,%20Maud,%22,%22limit%22:10,%22type%22:%22/people/person%22%7D%7D). So it appears the only choice is to not enable correction for this service.
