### ISSUE TITLE
Refine only works on 1st 7xx field

### ISSUE THREAD

**Issue by lrichelle** [ExLibrisGroup/alma-refine#15]
Hi,
Refinement search only takes 1st on several 7xx fields, which is a shame.

![Only-first-700](https://user-images.githubusercontent.com/73102583/107347666-5958e900-6ac6-11eb-97c1-5c2af4b4166c.png)

Is it a configuration  option or something you can improve ?

Thanks !
Have a nice day,
Laurence

**Comment by jweisman** [comment]
Hi @lrichelle . Thanks for your comment. I believe this issue was fixed. Please take a look at let us know.

**Comment by lrichelle** [comment]
Hi, yes, that's fixed, all 7xx fields are handled.
Many thanks !
Laurence

**Comment by jweisman** [comment]
Glad to hear. Thanks for the update.
