### ISSUE TITLE
Wikidata reconciliation: Support to add reconciliation service domain

### ISSUE THREAD

**Issue by jimfhahn** [ExLibrisGroup/alma-refine#27]
Would it be possible to add a service domain to point at a reconciliation service that is not the wikidata link.

E.g. in the  service URL:
<img width="217" alt="Screen Shot 2021-09-07 at 9 07 56 AM" src="https://user-images.githubusercontent.com/1310509/132350008-c9487436-154d-40c4-a3da-3ab82d08c23f.png">

This would be useful for making use of the standard endpoint pattern ( [https://github.com/wetneb/openrefine-wikibase](https://github.com/wetneb/openrefine-wikibase) ) that we point to a wikibase with entities we would like to reconcile that are not in wikidata.

**Comment by jweisman** [comment]
Hi- thanks for your suggestion. We can perhaps replace the existing Wikidata service with the new one. We'll explore to see if this is possible in the coming week or two.

**Comment by jimfhahn** [comment]
Thanks! What I'm hoping for is that the field could be modified by the Alma user who wants to point to their Wikibase endpoint. Our use case would involve pointing to a hosted Wikibase install or WbStack page other than Wikidata using the https://reconciliation-api.github.io/specs/latest/

**Comment by jweisman** [comment]
This is possible, although due to security concerns we would need to make a change to the refine app to go through a proxy. This is something we can consider if it's a need for you.

**Comment by jimfhahn** [comment]
Thank you -- yes, proxying is OK. 

We do have some anticipated upcoming uses. We have been modeling a Wikibase to be collaboratively edited by members of the [LD4 Wikibase Working Group](https://www.wikidata.org/wiki/Wikidata:WikiProject_LD4_Wikidata_Affinity_Group/Wikibase_and_WBStack_Working_Hours). Our plans are to host a reconcile endpoint pointing to this Wikibase, which will allow us to search and add alternative labels for LCSH from within Alma and AlmaRefine.

**Comment by jweisman** [comment]
Hi @jimfhahn - we created a [new version](https://github.com/ExLibrisGroup/alma-refine/releases/tag/v1.0.0) which allows adding a new refine service. Let us know how it goes for you.

Thanks.

**Comment by jimfhahn** [comment]
Thanks @jweisman the feature to add a reconciliation service is working. I tried out adding two different wikidata reconciliation endpoints and the reconciliation process is able to bring in potential matches. I believe that in order to make an accurate selection the service might need to allow the hover-over details w/ links populate through to the interface -- here is what I am seeing now:

<img width="1001" alt="Screen Shot 2021-10-04 at 8 39 51 AM" src="https://user-images.githubusercontent.com/1310509/135862010-7aeb777a-591f-43f6-905a-0a51ebdac7d0.png">

In the original service a details hover-over would be presented to help disambiguate the entity with other similarly names entities:

<img width="1001" alt="Screen Shot 2021-10-04 at 8 44 54 AM" src="https://user-images.githubusercontent.com/1310509/135862506-b4ee4c46-bedc-4f32-ae46-9a2b03bed1e1.png">

**Comment by jweisman** [comment]
Really glad it worked for you! 

We made a change which should allow the preview panes, even for custom refine sources. Please give it a try.

**Comment by jimfhahn** [comment]
Thank you! I am now able to see the preview detail panes.

**Comment by jweisman** [comment]
Great!
